<MyItem>:
    cols: 3
    width: 200
    adaptive_width: True
    MDLabel:
        text: '1'
        id: name_instr
    MDLabel:
        id: addr_instr
        text: '1'
    MDLabel:
        id: user_label
        text: '1'

<CustomItem>:
    on_size:
        self.ids._right_container.width = container.width
        self.ids._right_container.x = container.width
    disabled: True
    MyItem:
        id:container
